[package]
name = "libp2p-tls-quic"
version = "0.1.0"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2018"
license = "MIT"
description = "A libp2p transport using TLS+QUIC"
keywords = ["peer-to-peer", "libp2p", "quic", "networking"]
categories = ["network-programming", "asynchronous"]

[dependencies]
# TODO: update all these deps to match rest of rust-libp2p
libp2p-core = { path = "../../core", version = "0.29.0" }
rcgen = "0.8.11"
x509-parser = { version = "0.9.2", features = ["verify"] }
der-parser = { version = "5.1.0", features = ["serialize"] }
yasna = "0.4.0"
