[package]
name = "libp2p-quic"
version = "0.7.0"
authors = ["David Craven <david@craven.ch>", "Parity Technologies <admin@parity.io>"]
edition = "2021"
description = "TLS based QUIC transport implementation for libp2p"
repository = "https://github.com/libp2p/rust-libp2p"
license = "MIT"

[dependencies]
async-global-executor = "2.0.2"
async-io = "1.6.0"
futures = "0.3.15"
if-watch = "1.0.0"
libp2p-core = { version = "0.34.0", path = "../../core" }
parking_lot = "0.12.0"
quinn-proto = { version = "0.8.2", default-features = false, features = ["tls-rustls"] }
rcgen = "0.9.2"
ring = "0.16.20"
rustls = { version = "0.20.2", default-features = false, features = ["dangerous_configuration"] }
thiserror = "1.0.26"
tracing = "0.1.30"
webpki = "0.22.0"
x509-parser = "0.14.0"
yasna = "0.5.0"

[dev-dependencies]
anyhow = "1.0.41"
async-std = { version = "1.10.0", features = ["attributes"] }
async-trait = "0.1.50"
libp2p = { version = "0.47.0", default-features = false, features = ["request-response"], path = "../.." }
rand = "0.8.4"
tracing-subscriber = {version = "0.3.8", features = ["env-filter"] }
quickcheck = "1"
