[package]
name = "libp2p-quic"
version = "0.6.0"
authors = ["David Craven <david@craven.ch>", "Parity Technologies <admin@parity.io>"]
edition = "2018"
description = "TLS based QUIC transport implementation for libp2p"
repository = "https://github.com/libp2p/rust-libp2p"
license = "MIT"

[dependencies]
async-global-executor = "2.0.2"
async-io = "1.6.0"
bytes = "1.0.1"
der-parser = { version = "6.0.0", default-features = false }
futures = "0.3.15"
if-watch = "0.2.2"
libp2p-core = { version = "0.31.0", path = "../../core" }
parking_lot = "0.11.1"
quinn-proto = { version = "0.8.0", default-features = false, features = ["tls-rustls"] }
rcgen = { version = "0.8.11" }
ring = { version = "0.16.20" }
rustls = { version = "0.20.2", default-features = false, features = ["dangerous_configuration"] }
thiserror = "1.0.26"
tracing = "0.1.30"
udp-socket = "0.1.5"
webpki = "0.22.0"
x509-parser = "0.12.0"
yasna = { version = "0.4.0" }

async-std = "*"
futures-timer = "*"

[dev-dependencies]
anyhow = "1.0.41"
async-std = { version = "1.10.0", features = ["attributes"] }
async-trait = "0.1.50"
async-macros = "*"
libp2p = { version = "0.42.0", default-features = false, features = ["request-response"], path = "../.." }
log-panics = "2.0.0"
rand = "0.8.4"
rand_core = "0.5.1"
tracing-subscriber = {version = "0.3.8", features = ["env-filter"] }
tracing-flame = "0.2"
quickcheck = "1"
